### PR TITLE
Linux support

### LINKED ISSUE #3: Linux support
I have tested cef-sys bindings on Mac and Windows, but I need to run rust-bindgen on Linux before it will work on that platform.

### PR DESCRIPTION
**Pull request by dylanede**
Once tested, this should fix #3.

### CODE REVIEW

**Comment by palodequeso** [comment]
When I run the build, it looks like it's pulling cef-sys from a repo rather than the local copy.

```
[20:19:39] douglas@douglas-lappy:~/Projects/external/cef-rs$ cargo build
    Updating git repository `https://github.com/dylanede/callc.git`
    Updating registry `https://github.com/rust-lang/crates.io-index`
    Updating git repository `https://github.com/dylanede/cef-rs.git`
   Compiling cef-sys v0.0.3 (https://github.com/dylanede/cef-rs.git#b3a17901)
   Compiling callc v0.0.1 (https://github.com/dylanede/callc.git#40d85c4f)
   Compiling bitflags v0.1.1
Build failed, waiting for other jobs to finish...
failed to run custom build command for `cef-sys v0.0.3 (https://github.com/dylanede/cef-rs.git#b3a17901)`
Process didn't exit successfully: `/home/douglas/Projects/external/cef-rs/target/build/cef-sys-9d8dba5d676bc4bd/build-script-build` (status=101)
--- stderr
thread '<main>' panicked at 'Sorry, Linux is not supported until bindings for CEF for that platform are generated.', /home/douglas/.cargo/git/checkouts/cef-rs-e7a834e033e33c71/master/cef-sys/build.rs:25
```

**Comment by bombless** [comment]
Yeah, I've been always curious why not just add a `path` for dependency instead of adding a `git`.

**Comment by dylanede** [comment]
Ah, the non-relative path is a leftover of when cef-sys was in a different repo. Fixed. Try it now.

**Comment by palodequeso** [comment]
Looks like an unresolved name doth linger...
```
[08:43:38] douglas@douglas-lappy:~/Projects/external/cef-rs$ CEF_PATH=/home/douglas/Downloads/cef/Release cargo build --verbose
       Fresh bitflags v0.1.1
       Fresh callc v0.0.1 (https://github.com/dylanede/callc.git#40d85c4f)
       Fresh cef-sys v0.0.3 (file:///home/douglas/Projects/external/cef-rs)
   Compiling cef v0.0.1 (file:///home/douglas/Projects/external/cef-rs)
     Running `rustc src/lib.rs --crate-name cef --crate-type lib -g -C metadata=47c44e645c7bf7d0 -C extra-filename=-47c44e645c7bf7d0 --out-dir /home/douglas/Projects/external/cef-rs/target --emit=dep-info,link -L dependency=/home/douglas/Projects/external/cef-rs/target -L dependency=/home/douglas/Projects/external/cef-rs/target/deps --extern cef-sys=/home/douglas/Projects/external/cef-rs/target/deps/libcef-sys-066604ab24342fd3.rlib --extern callc=/home/douglas/Projects/external/cef-rs/target/deps/libcallc-a8263d564e0e20e2.so --extern bitflags=/home/douglas/Projects/external/cef-rs/target/deps/libbitflags-518ea12e21428edd.rlib -L /home/douglas/Downloads/cef/Release`
src/lib.rs:355:9: 355:20 error: unresolved name `os_specific`
src/lib.rs:355         os_specific(&mut info, self.windowless_rendering_enabled);
                       ^~~~~~~~~~~
error: aborting due to previous error
Could not compile `cef`.

Caused by:
  Process didn't exit successfully: `rustc src/lib.rs --crate-name cef --crate-type lib -g -C metadata=47c44e645c7bf7d0 -C extra-filename=-47c44e645c7bf7d0 --out-dir /home/douglas/Projects/external/cef-rs/target --emit=dep-info,link -L dependency=/home/douglas/Projects/external/cef-rs/target -L dependency=/home/douglas/Projects/external/cef-rs/target/deps --extern cef-sys=/home/douglas/Projects/external/cef-rs/target/deps/libcef-sys-066604ab24342fd3.rlib --extern callc=/home/douglas/Projects/external/cef-rs/target/deps/libcallc-a8263d564e0e20e2.so --extern bitflags=/home/douglas/Projects/external/cef-rs/target/deps/libbitflags-518ea12e21428edd.rlib -L /home/douglas/Downloads/cef/Release` (status=101)
```

**Comment by palodequeso** [comment]
I added
```
        #[cfg(target_os="linux")]
        fn os_specific(info: &mut ffi::cef_window_info_t, windowless: bool) {
            //
        }
```

to lib.rs just to get further in the build and ran into another set of errors...
```
[08:44:00] douglas@douglas-lappy:~/Projects/external/cef-rs$ CEF_PATH=/home/douglas/Downloads/cef/Release cargo build --verbose
       Fresh bitflags v0.1.1
       Fresh cef-sys v0.0.3 (file:///home/douglas/Projects/external/cef-rs)
       Fresh callc v0.0.1 (https://github.com/dylanede/callc.git#40d85c4f)
   Compiling cef v0.0.1 (file:///home/douglas/Projects/external/cef-rs)
     Running `rustc src/lib.rs --crate-name cef --crate-type lib -g -C metadata=47c44e645c7bf7d0 -C extra-filename=-47c44e645c7bf7d0 --out-dir /home/douglas/Projects/external/cef-rs/target --emit=dep-info,link -L dependency=/home/douglas/Projects/external/cef-rs/target -L dependency=/home/douglas/Projects/external/cef-rs/target/deps --extern cef-sys=/home/douglas/Projects/external/cef-rs/target/deps/libcef-sys-066604ab24342fd3.rlib --extern callc=/home/douglas/Projects/external/cef-rs/target/deps/libcallc-a8263d564e0e20e2.so --extern bitflags=/home/douglas/Projects/external/cef-rs/target/deps/libbitflags-518ea12e21428edd.rlib -L /home/douglas/Downloads/cef/Release`
src/browser_client/render_handler.rs:362:40: 362:61 error: mismatched types:
 expected `extern "C" fn(*mut cef-sys::linux::Struct__cef_render_handler_t, *mut cef-sys::linux::Struct__cef_browser_t, u64, u32, *const cef-sys::linux::Struct__cef_cursor_info_t)`,
    found `extern "C" fn(*mut cef-sys::linux::Struct__cef_render_handler_t, *mut cef-sys::linux::Struct__cef_browser_t, *mut libc::types::common::c95::c_void, u32, *const cef-sys::linux::Struct__cef_cursor_info_t) {browser_client::render_handler::RenderHandlerWrapper<T>::new::on_cursor_change}`
(expected u64,
    found *-ptr) [E0308]
src/browser_client/render_handler.rs:362                 on_cursor_change: Some(on_cursor_change::<T>),
                                                                                ^~~~~~~~~~~~~~~~~~~~~
src/lib.rs:335:18: 335:24 error: mismatched types:
 expected `u32`,
    found `i32`
(expected u32,
    found i32) [E0308]
src/lib.rs:335         info.x = self.x;
                                ^~~~~~
src/lib.rs:336:18: 336:24 error: mismatched types:
 expected `u32`,
    found `i32`
(expected u32,
    found i32) [E0308]
src/lib.rs:336         info.y = self.y;
                                ^~~~~~
src/lib.rs:337:22: 337:32 error: mismatched types:
 expected `u32`,
    found `i32`
(expected u32,
    found i32) [E0308]
src/lib.rs:337         info.width = self.width;
                                    ^~~~~~~~~~
src/lib.rs:338:23: 338:34 error: mismatched types:
 expected `u32`,
    found `i32`
(expected u32,
    found i32) [E0308]
src/lib.rs:338         info.height = self.height;
                                     ^~~~~~~~~~~
src/lib.rs:342:13: 342:29 error: attempted access of field `window_name` on type `cef-sys::linux::Struct__cef_window_info_t`, but no field with that name was found
src/lib.rs:342             info.window_name = CefString::from_str(name).cast()
                           ^~~~~~~~~~~~~~~~
src/lib.rs:342:18: 342:29 help: did you mean `window`?
src/lib.rs:342             info.window_name = CefString::from_str(name).cast()
                                ^~~~~~~~~~~
error: aborting due to 6 previous errors
Could not compile `cef`.

Caused by:
  Process didn't exit successfully: `rustc src/lib.rs --crate-name cef --crate-type lib -g -C metadata=47c44e645c7bf7d0 -C extra-filename=-47c44e645c7bf7d0 --out-dir /home/douglas/Projects/external/cef-rs/target --emit=dep-info,link -L dependency=/home/douglas/Projects/external/cef-rs/target -L dependency=/home/douglas/Projects/external/cef-rs/target/deps --extern cef-sys=/home/douglas/Projects/external/cef-rs/target/deps/libcef-sys-066604ab24342fd3.rlib --extern callc=/home/douglas/Projects/external/cef-rs/target/deps/libcallc-a8263d564e0e20e2.so --extern bitflags=/home/douglas/Projects/external/cef-rs/target/deps/libbitflags-518ea12e21428edd.rlib -L /home/douglas/Downloads/cef/Release` (status=101)
```

I'll tinker with that a bit as well.

**Comment by dylanede** [comment]
So close (I hope)! I'll see if I can get it to produce these errors my end and try and fix it.

**Comment by palodequeso** [comment]
It would be super easy to fire up a VM on VirtualBox to do this, especially since I already generated the bindgen ffi.rs file.

**Comment by dylanede** [comment]
I did as you suggested. I've fixed the conflicts and tested it. I'll wait until you can confirm that it works before closing.

**Comment by palodequeso** [comment]
It compiles just fine on my end now, good work!

**Comment by palodequeso** [comment]
I also tested and ran the example, it worked fine. :+1:

**Comment by dylanede** [comment]
I'll double check that this hasn't broken anything for Windows and Mac, then I'll merge.

**Comment by palodequeso** [comment]
Sweet!

**Comment by palodequeso** [comment]
As soon as it's in I plan to start integrating into my game engine, so you should definitely post  your glium example again. :)

**Comment by dylanede** [comment]
I must warn you that I am still working on getting all user input transferred from glutin into CEF (and support for that is not yet in the main repo), so it won't have any practical uses until that is done. Keyboard input in particular is a pain.

Anyway, it works on Mac, Windows and Linux, so I'm merging! Make sure to use the latest nightly.

**Comment by palodequeso** [comment]
Can you put up your glium usage gist again? I'd really like to integrate this.

**Pull request merged**
